# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Bloret.Launcher
PackageVersion: "5"
InstallerLocale: zh-CN
InstallerType: msi
ProductCode: '{C328F29C-5125-47FA-830B-E58359DCBC66}'
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/BloretCrew/Bloret-Launcher/releases/download/5/Bloret-Launcher.msi
  InstallerSha256: 36E8ABDF6B063C4092D98139940AC51AE05B15F5849D03F559905492A4BA751D
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-04-09
