# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Bloret.BloretLauncher
PackageVersion: "5"
InstallerLocale: zh-CN
InstallerType: msi
ProductCode: '{C328F29C-5125-47FA-830B-E58359DCBC66}'
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/BloretCrew/Bloret-Launcher/releases/download/5/Bloret.Launcher.msi
  InstallerSha256: 64E74A95CEA4988DA82A2E7345BD6F1FE8EDFD4B109F98741C669D6F3C2DCB57
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-04-05
